"""
gemini_bridge/tools/base.py
----------------------------
Shared type definitions and helper for all MCP tools.

Responsibilities:
  - Define ToolResult type alias (return type for all tool handlers)
  - Define ThinkingParam type alias (optional thinking level parameter)
  - Provide call_gemini() helper that combines ask() + transcript append

Design notes:
  - Interface Segregation: tools import only what they need from here; no server/config exposure
  - Single Responsibility: shared plumbing only — no tool-specific logic lives here
  - Liskov Substitution: all tools return ToolResult; callers are agnostic to which tool ran

Raises:
  (none directly) — call_gemini() surfaces ClientError messages as ToolResult strings

Used by:  tools/ask.py, tools/brainstorm.py, tools/review.py, tools/debug.py, tools/architect.py
Imports:  client.py (GeminiClient), transcript.py (TranscriptWriter), config.py (ThinkingLevel)
"""

import logging
from typing import Optional

from gemini_bridge.client import FALLBACK_MODEL, ClientError, GeminiClient, _is_retryable

_log = logging.getLogger(__name__)
from gemini_bridge.config import ThinkingLevel
from gemini_bridge.transcript import TranscriptWriter

# Return type for all MCP tool handlers.
ToolResult = str

# Optional thinking level parameter type accepted by every tool.
ThinkingParam = Optional[ThinkingLevel]


def call_gemini(
    client: GeminiClient,
    transcript: TranscriptWriter,
    tool_name: str,
    session_name: str,
    system_instruction: str,
    prompt: str,
    thinking: ThinkingParam,
    model: Optional[str] = None,
) -> ToolResult:
    """Get a session, call ask(), log to transcript, return response or error string.

    If the requested model returns a terminal overload error (503/429 after retries),
    automatically retries once against FALLBACK_MODEL and prefixes the response with a
    visible notice so Claude and the user know a substitution occurred.
    """
    effective_thinking: ThinkingLevel = thinking or client.default_thinking
    _log.debug(
        "%s session=%r model=%s thinking=%s",
        tool_name,
        session_name,
        model or "default",
        effective_thinking,
    )

    def _do_ask(use_model: Optional[str]) -> str:
        session = client.get_or_create_session(
            name=f"{tool_name}:{session_name}",
            system_instruction=system_instruction,
            model=use_model,
        )
        return client.ask(
            session, prompt, thinking, system_instruction=system_instruction, model=use_model
        )

    fallback_notice: Optional[str] = None
    try:
        response = _do_ask(model)
    except ClientError as exc:
        # If retryable and a different model was requested, try the stable fallback once.
        requested = model or FALLBACK_MODEL
        if _is_retryable(exc) and requested != FALLBACK_MODEL:
            _log.warning(
                "%s: model %r overloaded — falling back to %r",
                tool_name,
                requested,
                FALLBACK_MODEL,
            )
            try:
                response = _do_ask(FALLBACK_MODEL)
                fallback_notice = (
                    f"[gemini-bridge notice] Model '{requested}' was unavailable (503/429); "
                    f"this response was generated by fallback model '{FALLBACK_MODEL}'.\n\n"
                )
            except ClientError as fallback_exc:
                _log.error("%s fallback also failed: %s", tool_name, fallback_exc)
                return f"[gemini-bridge error] {exc} (fallback also failed: {fallback_exc})"
        else:
            _log.error("%s session=%r failed: %s", tool_name, session_name, exc)
            return f"[gemini-bridge error] {exc}"

    _log.debug("%s session=%r OK", tool_name, session_name)
    transcript.append(
        tool_name=tool_name,
        prompt=prompt,
        response=response,
        thinking=effective_thinking,
        session=session_name,
    )
    if fallback_notice:
        return f"{fallback_notice}{response}"
    return response
